export const COFFEEDATA = "COFFEEDATA";
export const EMPLOYEEDATA = "EMPLOYEEDATA";
export const RESTAURANTDATA = "RESTAURANTDATA";
export const ISLOADING = "ISLOADING";
export const ISERROR = "ISERROR";
